//go:build !ignore_autogenerated

/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and component-operator-runtime contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package manifests

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizeImage) DeepCopyInto(out *KustomizeImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizeImage.
func (in *KustomizeImage) DeepCopy() *KustomizeImage {
	if in == nil {
		return nil
	}
	out := new(KustomizeImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizePatch) DeepCopyInto(out *KustomizePatch) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(KustomizeSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizePatch.
func (in *KustomizePatch) DeepCopy() *KustomizePatch {
	if in == nil {
		return nil
	}
	out := new(KustomizePatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizeSelector) DeepCopyInto(out *KustomizeSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizeSelector.
func (in *KustomizeSelector) DeepCopy() *KustomizeSelector {
	if in == nil {
		return nil
	}
	out := new(KustomizeSelector)
	in.DeepCopyInto(out)
	return out
}
