//go:build !ignore_autogenerated

/*
SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and component-operator-runtime contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package reconciler

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventoryItem) DeepCopyInto(out *InventoryItem) {
	*out = *in
	out.TypeInfo = in.TypeInfo
	out.NameInfo = in.NameInfo
	if in.ManagedTypes != nil {
		in, out := &in.ManagedTypes, &out.ManagedTypes
		*out = make([]TypeInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventoryItem.
func (in *InventoryItem) DeepCopy() *InventoryItem {
	if in == nil {
		return nil
	}
	out := new(InventoryItem)
	in.DeepCopyInto(out)
	return out
}
