name: Run Tests

on:
  pull_request:
    branches:
    - main
    paths:
    - website/**
    - .github/workflows/publish-website.yaml
    - README.md

defaults:
  run:
    shell: bash

jobs:
  test-scaffold:
    runs-on: ubuntu-22.04
    steps:
    - name: Skip the test
      run: 'echo "No test required"'
